# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('exam_title', models.TextField()),
                ('date', models.DateTimeField()),
                ('content_id', models.CharField(max_length=32)),
                ('channel_id', models.CharField(max_length=32)),
                ('question_count', models.IntegerField()),
                ('student_id', models.CharField(max_length=60)),
                ('correct_questions', models.IntegerField()),
                ('question_sources', models.TextField(default='')),
            ],
        ),
    ]
