# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20181003_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='id',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
