# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-11 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20181003_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_id',
            field=models.CharField(default='', max_length=60),
        ),
    ]
