# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-11 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='class_id',
        ),
    ]
