# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-16 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_exam_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='attempted_questions',
            field=models.IntegerField(default=0),
        ),
    ]
