# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-24 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20181017_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='attempted_questions',
        ),
    ]
