# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_remove_exam_attempted_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='content_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='class_id',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_sources',
            field=models.TextField(null=True),
        ),
    ]
