# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170830_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrolecollectionmapping',
            name='approver_id',
        ),
        migrations.RemoveField(
            model_name='userrolecollectionmapping',
            name='is_approved',
        ),
    ]
