# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180220_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterylevelclass',
            old_name='students_completed',
            new_name='mastered',
        ),
        migrations.RenameField(
            model_name='masterylevelschool',
            old_name='students_completed',
            new_name='mastered',
        ),
        migrations.RemoveField(
            model_name='masterylevelstudent',
            name='completed',
        ),
        migrations.AddField(
            model_name='content',
            name='sub_topics_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterylevelstudent',
            name='mastered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='latestfetchdate',
            name='date_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
