# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180306_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterylevelclass',
            name='attempt_exercise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterylevelschool',
            name='attempt_exercise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterylevelstudent',
            name='attempt_exercise',
            field=models.IntegerField(default=0),
        ),
    ]
