# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170830_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterylevelclass',
            name='class_id',
        ),
        migrations.DeleteModel(
            name='MasteryLevelClass',
        ),
    ]
