# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170831_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteryLevelClass',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('content_id', models.CharField(max_length=32)),
                ('channel_id', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('completed_questions', models.IntegerField(default=0)),
                ('correct_questions', models.IntegerField(default=0)),
                ('attempt_questions', models.IntegerField(default=0)),
                ('students_completed', models.IntegerField(default=0)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserInfoClass')),
            ],
        ),
    ]
