# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180312_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=60)),
                ('city_initial', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='parent_id',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfoschool',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userinfoschool',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
