# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_masterylevelclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolecollectionmapping',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserInfoClass'),
        ),
        migrations.AlterField(
            model_name='userrolecollectionmapping',
            name='institute_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserInfoSchool'),
        ),
    ]
