# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_userinfoschool_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfoschool',
            name='parent',
        ),
    ]
