# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_userinfoschool_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfoschool',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userinfoschool',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
