# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-11 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_auto_20190205_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='last_sync_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='', max_length=60)),
                ('class_name', models.CharField(max_length=60)),
                ('sync_date', models.DateField(default=datetime.date.today)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserInfoClass')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserInfoSchool')),
            ],
            options={
                'db_table': 'last_sync_date',
            },
        ),
    ]
