# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-12 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_report', '0002_remove_last_sync_date_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_sync_date',
            name='class_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='last_sync_date',
            name='school_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
