# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20180220_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_usage', models.IntegerField(default=0)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserInfoClass')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_usage', models.IntegerField(default=0)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserInfoSchool')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_usage', models.IntegerField(default=0)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserInfoStudent')),
            ],
        ),
    ]
