# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='total_usage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='total_usage',
            field=models.BigIntegerField(default=0),
        ),
    ]
