# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersession', '0002_auto_20180220_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_usage',
            field=models.BigIntegerField(default=0),
        ),
    ]
