# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=60)),
                ('class_id', models.IntegerField()),
                ('lesson_content', models.TextField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
